animal_shelter/animal_shelter/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from adoptions.views import AdoptionsViewSet, AnimalDetailView
from rest_framework.routers import SimpleRouter

router = SimpleRouter()
router.register('api/adoptions',AdoptionsViewSet, 'adoptions')


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html')),
    path('adopcje', TemplateView.as_view(template_name='adoptions.html'),name="adoptions"),
    path('adopcje/<int:pk>/', AnimalDetailView.as_view(), name='animal-detail'),
    path('adopcje', TemplateView.as_view(template_name='adoptions.html')),
    path('potrzeby/leki', TemplateView.as_view(template_name='meds.html')),
    path('potrzeby/leki', TemplateView.as_view(template_name='meds.html')),
    path('lapa/kontakt', TemplateView.as_view(template_name='contact.html'), name="contact"),
    path('lapa/o-nas', TemplateView.as_view(template_name='about.html'), name="about"),
    path('potrzeby/karma', TemplateView.as_view(template_name='food.html')),
    path('potrzeby/srodki-czystosci', TemplateView.as_view(template_name='cleaning.html')),

    *router.urls
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header  =  "Łapa Nysa"  
admin.site.site_title  =  "Łapa Nysa Panel Administratora"
admin.site.index_title  = "Administracja zwierzętami do adopcji" 

animal_shelter/adoptions/models.py
import tempfile
from uuid import uuid4
from django.db import models
from django.conf import settings
# Create your models here.
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Animal(BaseModel):
    class Meta:
        verbose_name="Zwierzę"
        verbose_name_plural="Zwierzęta"

    class Sex(models.TextChoices):
        MALE = 'male', 'Samiec'
        FEMALE = 'female', 'Samica'

    class Spices(models.TextChoices):
        DOG = 'dog', 'Pies'
        CAT = 'cat', 'Kot'
        OTHER = 'other', 'Inne'

    class Size(models.TextChoices):
        SMALL = 'small', 'Mały zwierzak'
        MEDIUM = 'medium', 'Średni zwierzak'
        LARGE = 'big', 'Duży zwierzak'

    def __str__(self) -> str:
        return f"{self.name}"

    name = models.CharField("Imię", max_length=50)
    spice = models.CharField("Gatunek",choices=Spices.choices, max_length=50)
    description = models.TextField("Opis")
    age = models.IntegerField("Wiek")
    weight = models.FloatField("Waga")
    additional_notes = models.TextField("Dodatkowe uwagi")
    sex = models.CharField("Płeć",choices=Sex.choices, max_length=50)
    breed = models.CharField("Rasa / W typie...", max_length=100)
    size = models.CharField("Rozmiar",choices=Size.choices, max_length=50)

    @property
    def form_link(self):
        if self.spice == self.Spices.DOG.value:
            return "https://docs.google.com/forms/d/1sGGmlt3Wqzu-qRTFG4Qc_WAcEAgpA0f-YAjghXE9M2w/viewform?fbclid=IwAR25QoCrvvyCUCH16lh619iFyWXn1qsQWAbH_5wu45db08gBsFe8pH9xNnw&edit_requested=true"
        return "https://docs.google.com/forms/d/1aZ7GuUAQWVyyvKXdQC6E3XYnZcDZb-lAZwv1acYJ0hU/viewform?fbclid=IwAR1g3G59ae7MPObycL8OnTEtfWBDceKvhw2t22RtXvhLVRtplxZt17U0t7g&edit_requested=true"

class Photo(BaseModel):
    class Meta:
        verbose_name="Zdjęcie"
        verbose_name_plural="Zdjęcia"
    image = models.ImageField("Zdjęcie")
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, related_name="photos")

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return settings.PROD_HOST + self.image.url
        return self.link

    def save(self, *args, **kwargs):
        from PIL import Image
        from io import BytesIO
        from django.core.files.uploadedfile import InMemoryUploadedFile
        from django.core.files.base import ContentFile
        from PIL.ImageOps import exif_transpose
        if self.image and self.image.name.split('.')[-1]!="webp":
            img = Image.open(
                self.image.file
            )
            image = img#.convert('RGB')
            basewidth = 1000
            wpercent = (basewidth/float(img.size[0]))
            hsize = int((float(img.size[1])*float(wpercent)))
            image = image.resize((basewidth,hsize), Image.ANTIALIAS)
            f = tempfile.TemporaryFile()

            buffer = BytesIO()
            image = exif_transpose(image)
            image.save(fp=buffer, format='webp')
            image=ContentFile(buffer.getvalue())
            self.image.save(
                f'{self.animal.name}_{self.id}.webp',
                InMemoryUploadedFile(
                    image,  # file
                    None,  # field_name
                    f'{self.animal.name}_{str(uuid4())}.webp',  # file name
                    'image/webp',  # content_type
                    image.tell,  # size
                    None,  # content_type_extra
                ),
            )
        super().save(*args, **kwargs)    

animal_shelter/adoptions/views.py
from rest_framework import viewsets, mixins, serializers
from adoptions.models import Animal, Photo

from django_filters import FilterSet
import django_filters
from django_filters import rest_framework as filters
from django.views import generic

# Create your views here.
class PhotoSerializer(serializers.ModelSerializer):
    class Meta:
        model=Photo
        fields="__all__"

class AnimalSerializer(serializers.ModelSerializer):
    photos = PhotoSerializer(many=True)
    class Meta:
        model=Animal
        fields="__all__"

class CharInFilter(django_filters.BaseInFilter, django_filters.CharFilter):
    pass

class AnimalFilterSet(FilterSet):
    spice = CharInFilter(lookup_expr='in')
    size = CharInFilter(lookup_expr='in')
    age_gte = django_filters.NumberFilter(field_name="age", lookup_expr='gte')
    age_lte = django_filters.NumberFilter(field_name="age", lookup_expr='lte')
    sex = CharInFilter(lookup_expr='in')



class AdoptionsViewSet(viewsets.GenericViewSet, mixins.ListModelMixin, mixins.RetrieveModelMixin):
    queryset = Animal.objects.all()
    serializer_class = AnimalSerializer
    filter_backends = [filters.DjangoFilterBackend]
    filterset_class = AnimalFilterSet

class AnimalDetailView(generic.DetailView):
    model = Animal
    template_name = 'animal.html'

animal_shelter/animal_shelter/templates/adoptions.html
{% extends "layout.html" %} {% load static %} {% block content %}
<div id="adoptions-seach"></div>
{% endblock %}


{%block breadcrumbs%}
<p class="serif-font"><a href="/">Strona główna</a> / <a href={% url 'adoptions' %}>Adopcje</a></p>
{% endblock %}

{% block opengraph %}
<meta property="og:title" content="Zwierzęta adopcyjne Łapy" />
<meta property="og:description" content="Lista zwierząt dostępnych do adopcji." />
<meta property="og:image" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:image:secure_url" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:url" content="https://www.lapa.nysa.pl/adopcje" />
<meta property="og:site_name" content="Stowarzyszenie Łapa" />
<meta property="og:image:type" content="image/svg" />
<meta
  property="og:image:alt"
  content="lapa logo: dog shaking hand with human"
/>
{% endblock opengraph %}

animal_shelter/animal_shelter/templates/animal.html
{% extends 'layout.html' %} 
{% block opengraph %}
<meta property="og:title" content="{{animal.name}}" />
<meta property="og:description" content="{{animal.description}}" />
<meta property="og:image" content="https://www.lapa.nysa.pl{{animal.photos.all.0.image.url}}" />
<meta property="og:image:secure_url" content="https://www.lapa.nysa.pl{{animal.photos.all.0.image.url}}" />
<meta property="og:url" content="https://www.lapa.nysa.pl{% url 'animal-detail' animal.id %}" />
<meta property="og:site_name" content="Stowarzyszenie Łapa" />
<meta property="og:image:type" content="image/webp" />
<meta
  property="og:image:alt"
  content="lapa logo: dog shaking hand with human"
/>
{% endblock opengraph %}

{% block page_title %}
{{animal.name}} - Stowarzyszenie Łapa
{% endblock page_title %}

{%block breadcrumbs%}
<p class="serif-font"><a href="/">Strona główna</a> / <a href={% url 'adoptions' %}>Adopcje</a> / <a href={% url 'animal-detail' animal.id %}> {{animal.name}} </a></p>
{% endblock %}

{% block content %}
<div>
  
  <h1 class="text-left mt-5 mb-3">{{animal.name}} ({{animal.age}} lat)</h1>
  <div class="row">
    <div class="col-12 col-lg-12">
      <div id="react-gallery"></div>
    </div>
    <div class="col-12 col-lg-12">
      <h1 class="text-center mt-5">Opis</h1>
      <div class="col-12 col-md-12">
        <p style="text-align: justify">{{animal.description}}</p>
      </div>

  <h1 class="text-center mt-5">Cechy</h1>
  <div class="row ps-4 pe-4">
    <ul>
      <li>W typie rasy {{animal.breed}}</li>
      <li>Wiek {{animal.age}} lat</li>
      <li>Płeć {{animal.get_sex_display}}</li>
      <li>Wielkość {{animal.get_size_display}}</li>
      <li>Waga {{animal.weight}} kg</li>
      <li>Dodatkowe uwagi {{animal.additional_notes}}</li>
    </ul>
  </div>
    </div>
  </div>
  {% comment %} <h1 class="text-center mt-5">Kontakt w sprawie adopcji</h1> {% endcomment %}
  <div class="d-flex justify-content-center mt-5">
    <a class="btn btn-primary btn-lg" href={{animal.form_link}}>
      Wypełnij ankietę adopcyjną
    </a>
    {% comment %} <ul>
      {% for contact in animal.contacts.all %}
      <li>{{contact.name}}: {{contact.phone_number}}</li>

      {% endfor %}
    </ul> {% endcomment %}
  </div>
</div>
{% endblock %}

animal_shelter/animal_shelter/templates/cleaning.html
{% extends "layout.html" %} {% load static %} 

{% block page_title %}
Potrzebne środki czystości - Stowarzyszenie Łapa
{% endblock page_title %}
{% block opengraph %}
<meta property="og:title" content="Środki czystości dla Łapy" />
<meta property="og:description" content="Lista środków czystości potrzebnych nam do prowadzenia działalności" />
<meta property="og:image" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:image:secure_url" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:url" content="https://www.lapa.nysa.pl/potrzeby/srodki-czystosci" />
<meta property="og:site_name" content="Stowarzyszenie Łapa" />
<meta property="og:image:type" content="image/svg" />
<meta
  property="og:image:alt"
  content="lapa logo: dog shaking hand with human"
/>
{% endblock opengraph %}
{% block content %}
<h2>Najpotrzebniejsze leki</h2>
<p>
  Poniżej znajduje się lista najbardziej potrzebnych leków, które na bieżąco są
  zużywane w naszym schronisku.
</p>
<ul>
  <li>
    <a
      href="https://clean24.pl/product-pol-58805-Rekawiczki-nitrylowe-jednorazowe-niebieskie-100-szt-S.html"
      target="blank"
      >Rękawiczki jednorazowe
    </a>
  </li>
  <li>
    <a
      href="https://sklep.mezopuls.pl/toniki-zele-pielegnacja/832-waciki-jednorazowe-z-wlokniny-05-kg.html"
      target="blank"
      >Waciki jednorazowe
    </a>
  </li>
  <li>
    <a
      href="https://krabb.pl/pl/p/40x60-100szt-Podklady-higieniczne-chlonne-Abena/254"
      target="blank"
      >Podkłady higieniczne
    </a>
  </li>
  <li>
    <a
      href="https://clean24.pl/product-pol-58998-Sterillhand-plyn-do-higienicznej-i-chirurgicznej-dezynfekcji-rak-5000-ml.html"
      target="blank"
      >Płyn do dezynfekcji
    </a>
  </li>
  <li>
    <a
      href="https://ecoshine.sklep.pl/pl/p/FLOOR-ORANGE-10L-Plyn-z-alkoholem-do-mycia-podlog-o-zapachu-pomaranczy/321"
      target="blank"
      >Płyn do podłóg
    </a>
  </li>
  <li>
    <a
      href="https://ecoshine.sklep.pl/pl/p/DISH-CLEANER-5L-Skoncentrowany-plyn-do-recznego-mycia-naczyn/18"
      target="blank"
      >Płyn do naczyń
    </a>
  </li>
  <li>
    <a
      href="https://www.rajapack.pl/higiena-catering/worki-na-smieci-odpady/worki-na-smieci_C205010.html"
      target="blank"
      >Worki na śmieci
    </a>
  </li>
  <li>
    <a href="https://higienasklep.pl/artykuly-papierowe/czysciwa.html"
      target="blank"
      >Ręczniki papierowe
    </a>
  </li>
  <li>
    <a href="https://higienasklep.pl/artykuly-papierowe/czysciwa.html"
      target="blank"
      >Ręczniki papierowe
    </a>
  </li>
  <li>Dowolne środki czystości.</li>
</ul>

<p class="font-medium">
  Adres do dostawy: Stowarzyszenie Łapa, ul.Grodkowska 61, 48-300 Nysa
</p>

Potrzebujemy też
<a href="/potrzeby/karma">karmy</a>,
<a href="/potrzeby/leki">leków</a>
{% endblock %} 
{% block patronite_title %} Nie wiesz czego aktualnie brakuje? 
{%endblock patronite_title %} 
{% block patronite_content %}
 Wciąż możesz pomóc!
Serwis patronite pozwala na wspiearnie nas dowolną kwotą co miesiąc. Twoja pomoc
ma znaczenie, dzięki niej, możemy utrzymać odpowiednie warunki sanitarne w
schronisku.
 {% endblock patronite_content %}

animal_shelter/animal_shelter/templates/contact.html
{% extends "layout.html" %} {% load static %}
{% block page_title %}
Kontakt - Stowarzyszenie Łapa
{% endblock page_title %}
{% block opengraph %}
<meta property="og:title" content="Kontakt" />
<meta property="og:description" content="Na tej stronie znajdują się dane kontaktowe do stowarzyszenia Łapa" />
<meta property="og:image" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:image:secure_url" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:url" content="https://www.lapa.nysa.pl/kontakt" />
<meta property="og:site_name" content="Stowarzyszenie Łapa" />
<meta property="og:image:type" content="image/svg" />
<meta
  property="og:image:alt"
  content="lapa logo: dog shaking hand with human"
/>
{% endblock opengraph %}
{%block breadcrumbs%}
<p class="serif-font"><a href="/">Strona główna</a> / <a href={% url 'contact' %}>Kontakt</a></p>
{% endblock %}
{% block content %}
<div class="row">
<div class="col-12 col-lg-6">
    <h1> Kontakt</h1>
    <p>
        Nyskie Pogotowie Opiekuńczo - Adopcyjne dla Zwierząt ŁAPA
      </p>
      <p>
        KRS: 0000483104<br/>
        REGON: 161560808<br/>
        NIP: 7532433223<br/>
      </p>
      <p>
        Mail: lapa.nysa@o2.pl</br>
        Tel: 783 587 695</br>
        Grodkowska 61 48-303 Nysa</br>
      </p>
</div>
<div class="col-12 col-lg-6 d-flex justify-content-center">
    <div class="mapouter"><div class="gmap_canvas"><iframe height="300px" id="gmap_canvas" src="https://maps.google.com/maps?q=Grodkowska%2061%20Nysa&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://fmovies-online.net">fmovies</a><br><style>.mapouter{position:relative;text-align:right;height:300px;width:300px;}</style><a href="https://www.embedgooglemap.net">google maps html widget</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:300px;width:300px;}</style></div></div>
</div>
</div>
{% endblock %} 
{% block patronite_title %} Jak możesz pomóc?
{% endblock patronite_title %}
 {% block patronite_content %} 
 Nasze stowarzyszenie utrzymuje się głównie z datków. Dzięki Twojej regularnej pomocy możemy wypełniać swoją misję najlepiej jak tylko się da.
 Zachęcamy do wspacia nas przez patronite, przelewów bezpośrednich lub przekazania nam 1% podatku.

{% endblock patronite_content %}

animal_shelter/animal_shelter/templates/food.html
{% extends "layout.html" %} {% load static %}
{% block page_title %}
Potrzebne karmy - Stowarzyszenie Łapa
{% endblock page_title %}
{% block opengraph %}
<meta property="og:title" content="Karma dla Łapy" />
<meta property="og:description" content="Lista karm potrzebnych nam do prowadzenia działalności" />
<meta property="og:image" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:image:secure_url" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:url" content="https://www.lapa.nysa.pl/potrzeby/karma" />
<meta property="og:site_name" content="Stowarzyszenie Łapa" />
<meta property="og:image:type" content="image/svg" />
<meta
  property="og:image:alt"
  content="lapa logo: dog shaking hand with human"
/>
{% endblock opengraph %}
{% block content %}
<h2>Karma dla zwierząt</h2>
<p>
  Aby uniknąć problemów zdrowotnych u naszych podopiecznych, staramy się używać karmy wyższej jakości.
  Dziękujemy za nawet najmniejszą paczkę mięsnej karmy! Poniżej znajduje się lista sprawdzonych karm,
  które zapobiegają problemom żołądkowym naszych podopiecznych.
</p>
<h2>Dla psiaków</h2>
<ul>
  <li>
    <a
      href="https://www.zooplus.pl/shop/psy/karma_dla_psa_mokra/dolina_noteci/adult/976866"
      target="blank"
      >Dolina Noteci 
    </a>
  </li>
  <li>
    <a
      href="https://www.zooplus.pl/shop/psy/karma_dla_psa_sucha/bosch/1231319"
      target="blank"
      >Bosch 
    </a>
  </li>
  <li>
    <a
      href="https://www.zooplus.pl/shop/psy/karma_dla_psa_mokra/rocco/classic/46004"
      target="blank"
      >Royal Canin  
    </a>
  </li>
  <li>
    <a
      href="https://www.zooplus.pl/shop/psy/karma_dla_psa_mokra/animonda/pakiety_probne/1031511"
      target="blank"
      >Flora 
    </a>
  </li>
</ul>
<h2>Dla psiaków po przejściach</h2>
<ul>
  <li>
    <a
      href="https://www.zooplus.pl/shop/psy/karma_dla_psa_mokra/royalcanin_veterinary_diet/recovery/701579"
      target="blank"
      >Royal Canin Recovery 
    </a>
  </li>
  <li>
    <a
      href="https://www.zooplus.pl/shop/psy/karma_dla_psa_sucha/royal_canin_veterinary_diet/hypoallergenic/306872"
      target="blank"
      >Royal Canin Hypoallergenic 
    </a>
  </li>
  <li>
    <a
      href="https://www.dolina-noteci.pl/product-pol-1230-Mokra-karma-dla-psow-rekonwalescentow-Dolina-Noteci-Premium-Perfect-Care-Recovery-zestaw-12-x-185-g.html"
      target="blank"
      >Dolina Noteci Recovery
    </a>
  </li>
</ul>
<h2>Dla kotów</h2>
<ul>
  <li>
    <a
      href="https://www.zooplus.pl/shop/koty/bezzbozowe/mokra/337211"
      target="blank"
      >Smilla
    </a>
  </li>
  <li>
    <a
      href="https://www.zooplus.pl/shop/koty/bezzbozowe/mokra/374429"
      target="blank"
      >Feringa
    </a>
  </li>
  <li>
    <a
      href="https://www.zooplus.pl/shop/koty/karma_dla_kota_mokra/purizon/adult/1224918"
      target="blank"
      >Purizon
    </a>
  </li>
  <li>
    <a
      href="https://www.zooplus.pl/shop/koty/karma_dla_kota_mokra/dolina_noteci/adult/976658"
      target="blank"
      >Dolina Noteci 
    </a>
  </li>
</ul>
<h2>Dla kotów po przejściach</h2>
<ul>
  <li>
    <a
      href="https://www.zooplus.pl/shop/koty/karmy_specjalistyczne/uklad_moczowy_i_nerki/schorzenia_nerek/473362"
      target="blank"
      >Royal Canin Veterinary 
    </a>
  </li>
  <li>
    <a
      href="https://www.zooplus.pl/shop/koty/karmy_specjalistyczne/uklad_moczowy_i_nerki/schorzenia_nerek/1298830"
      target="blank"
      >Smilla Veterinary 

    </a>
  </li>
  <li>
    <a
      href="https://vetexpert.eu/sklep/hypoallergenic-cat-mokra-karma-weterynaryjna-dla-kotow-pakiet-6x100g.html"
      target="blank"
      >VetExpert Hypoallergenic 
    </a>
  </li>
  <li>
    <a
      href="https://vetexpert.eu/sklep/intestinal-cat-mokra-karma-weterynaryjna-dla-kotow-pakiet-6x100g.html"
      target="blank"
      >VetExpert Intenstinal 
    </a>
  </li>
</ul>
<p class="font-medium">
  Adres do dostawy: Stowarzyszenie Łapa, ul.Grodkowska 61, 48-300 Nysa
</p>

Potrzebujemy też
<a href="/potrzeby/leki">leków</a>,
<a href="/potrzeby/srodki-czystosci">środków czystości</a>
{% endblock %} 
{% block patronite_title %} Nie możesz się zdecydować? 
{% endblock patronite_title %}
 {% block patronite_content %} 
 Nic nie szkodzi! Zachęcamy do wspierania nas na patronite. Dzięki temu możemy na bieżąco 
 monitorować i uzupełniać stany magazynowe najpotrzebniejszych rodzajów.
{% endblock patronite_content %}

animal_shelter/animal_shelter/templates/meds.html
{% extends "layout.html" %} {% load static %} 
{% block page_title %}
Potrzebne leki - Stowarzyszenie Łapa
{% endblock page_title %}
{% block opengraph %}
<meta property="og:title" content="Leki dla Łapy" />
<meta property="og:description" content="Lista leków potrzebnych nam do prowadzenia działalności" />
<meta property="og:image" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:image:secure_url" content="https://www.lapa.nysa.pl{% static 'public/logo.svg' %}" />
<meta property="og:url" content="https://www.lapa.nysa.pl/potrzeby/karma" />
<meta property="og:site_name" content="Stowarzyszenie Łapa" />
<meta property="og:image:type" content="image/svg" />
<meta
  property="og:image:alt"
  content="lapa logo: dog shaking hand with human"
/>
{% endblock opengraph %}
{% block content %}
<h2>Najpotrzebniejsze leki</h2>
<p>
  Poniżej znajduje się lista najbardziej potrzebnych leków, które na bieżąco są
  zużywane w naszym schronisku.
</p>
<ul>
  <li>
    <a
      href="https://zooart.com.pl/product-pol-18133-VETFOOD-FLORA-Balance-60-caps.html"
      target="blank"
      >Flora Balance
    </a>
  </li>
  <li>
    <a href="https://zoona.pl/pl_PL/products/vetfood-flexactiv-120-kapsulek"
      target="blank"
      >FlexActive</a
    >
  </li>
  <li>
    <a href="https://zoona.pl/pl_PL/products/hemoactiv-blister-60-caps"
      target="blank"
      >HemoActive</a
    >
  </li>
  <li>
    <a
      href="https://zooart.com.pl/product-pol-47566-VETEXPERT-VetoSkin-60-kapsulek.html"
      target="blank"
      >VetoSkin</a
    >
  </li>
  <li>
    <a
      href="https://zooart.com.pl/product-pol-19398-VETEXPERT-VetoMune-60kaps.html"
      target="blank"
      >VetoMune</a
    >
  </li>
</ul>
<p class="font-medium">
  Adres do dostawy: Stowarzyszenie Łapa, ul.Grodkowska 61, 48-300 Nysa
</p>

Potrzebujemy też
<a href="/potrzeby/karma">karmy</a>,
<a href="/potrzeby/srodki-czystosci">środków czystości</a>
{% endblock %} 
{% block patronite_title %} Chcesz pomóc w inny sposób? 
{% endblock patronite_title %}
 {% block patronite_content %} Dostępność leków to
jeden z wielu problemów, z jakimi mierzy się codziennie Łapa. Dzięki waszym
wpłatom możemy rozwiązać większość z nich. Możesz zacząć pomagać już od 5 zł
miesięcznie, to tyle co mała kawa! 
{% endblock patronite_content %}